### ISSUE TITLE
server正常吗

### ISSUE THREAD

**Issue by styfstr** [wwhai/opcua-server-emulator#1]
兄弟，你这sever测试来没有，可以正常连接吗？我用uaexpert连接，一直失败。
![image](https://user-images.githubusercontent.com/44523785/155151911-f2cade68-62d2-46a7-a13c-0f7a3397b515.png)

**Comment by wwhai** [comment]
得改一把代码

**Comment by styfstr** [comment]
如何改，可以简单说一下思路吗？
我用github.com/gopcua/opcua这个库模拟过server，也没有连接成功。看他代码好像只支持opc-client，opc-server没有做好


| |
李春辉
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年2月22日 ***@***.***> 写道：

得改一把代码

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wwhai** [comment]
> 如何改，可以简单说一下思路吗？ 我用github.com/gopcua/opcua这个库模拟过server，也没有连接成功。看他代码好像只支持opc-client，opc-server没有做好 | | 李春辉 | | ***@***.*** | 签名由网易邮箱大师定制 在2022年2月22日 ***@***.***> 写道： 得改一把代码 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

不妨试试这个？反正是模拟测试用的
